[profile.default]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
single_quotes = false
